options:
  port:
    type: int
    default: 80
    description: Port on which to listen.
  nextcloud_domain:
    type: string
    default: 'nextcloud.example.com'
    description: 'The domain for the nextcloud server using collabora'
