options:
  port:
    type: int
    default: 80
    description: Port on which to listen.
  nextcloud_domain:
    type: string
    default: 'nextcloud.example.com'
    description: 'loolwsd.xml domain (your nextcloud server.)'
  ssl_enable:
    type: boolean
    default: False
    description: 'loolwsd.xml ssl.enabled option.'
  ssl_termination:
    type: boolean
    default: True
    description: 'loolwsd.xml ssl.termination option'
